[package]
name = "raytracer"
version = "0.1.0"
authors = ["Logitao <gmdramos@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fast_inv_sqrt = "1.0.1"

[profile.release]
opt-level = 3
